# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - denwebapp34

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_66334e1bcdf7446ab916e586d60c1196 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b7d2214ea716444591c0a0062e84d888 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_66334e1bcdf7446ab916e586d60c1196 }}/aci-helloworld:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'denwebapp34'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9a34afe408d14fc58932313f55a128cc }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_66334e1bcdf7446ab916e586d60c1196 }}/aci-helloworld:${{ github.sha }}'